name: 'data_stack_toolbox'

config-version: 2
version: '0.1'

profile: 'data_stack_toolbox'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

seeds: 
  +docs:
    node_color: '#cd7f32'

snapshots:
  data_stack_toolbox:
    +schema: snapshots

models:
  data_stack_toolbox:
    materialized: table
    core:
      +docs:
        node_color: 'gold'
    intermediate:
      materialized: view
      +docs:
        node_color: 'silver'
    staging:
      materialized: view
      +docs:
        node_color: 'bronze'
    +docs:
      node_color: 'gold'
